### ISSUE TITLE
Latest Proxyquireify is now 3.0.0, which proxyquire-universal does not like

### ISSUE THREAD

**Issue by SwiftOne** [bendrucker/proxyquire-universal#13]
Per the Readme:

[17:58:14]$  npm install --save-dev proxyquire-universal proxyquire proxyquireify
npm ERR! peerinvalid The package proxyquireify does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer proxyquire-universal@1.0.7 wants proxyquireify@>= 1 < 3

**Comment by bendrucker** [comment]
See #12, working on it
