### ISSUE TITLE
Peer proxyquire-universal@1.0.7 wants proxyquireify@>= 1 < 3

### ISSUE THREAD

**Issue by ch1bo** [bendrucker/proxyquire-universal#14]
Hey, just encountered an invalid peer depencency when installing all three modules like in the README:
```
npm install --save-dev proxyquire-universal proxyquire proxyquireify
```
Obviously its because the latest version of `proxyquireify` is now `3.0`.

**Comment by bendrucker** [comment]
Dupe of #12, #13
