### ISSUE TITLE
Run as transform instead of plugin?

### ISSUE THREAD

**Issue by TheSavior** [bendrucker/proxyquire-universal#15]
We are using babelify to convert JSX and proxyquire-universal. Since proxyquire-universal wants to be specified as a plugin, that causes it to be run before babelify. This causes browserify to error with parse errors. 

Is there any way to specify proxyquire-universal in the list of transforms instead of as a plugin so that it can be listed after babelify?

**Comment by bendrucker** [comment]
Sure, just `require('proxyquire-universal/transform')`. You'll have to register proxyquireify yourself. I think it should work.
