### ISSUE TITLE
Karma config

### ISSUE THREAD

**Issue by matfish2** [bendrucker/proxyquire-universal#17]
Trying to use proxyquire-universal with karma but get this error message:

`TypeError: b.transform is not a function
  at module.exports (/Users/matanya/Sites/vue-tables/resources/assets/js/node_modules/proxyquire-universal/index.js:6:5)
  at nr (/Users/matanya/Sites/vue-tables/resources/assets/js/node_modules/module-deps/index.js:289:23)
  at onfile (/Users/matanya/Sites/vue-tables/resources/assets/js/node_modules/resolve/lib/async.js:51:21)
  at onex (/Users/matanya/Sites/vue-tables/resources/assets/js/node_modules/resolve/lib/async.js:93:22)
  at /Users/matanya/Sites/vue-tables/resources/assets/js/node_modules/resolve/lib/async.js:24:18
  at FSReqWrap.oncomplete (fs.js:82:15)`

Karma config:

    module.exports = function(config) {
     config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine','browserify'],

    // list of files / patterns to load in the browser
    files: [
    'index.js',
    'lib/**/*.js',
    'tests/acceptance/**/*.js',
    'tests/unit/**/*.js'
    ],

    // list of files to exclude
    exclude: [
    ],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
     'index.js': ['browserify'],
     'lib/**/*.js': ['browserify'],
     'tests/acceptance/**/*.js': [ 'browserify' ],
     'tests/unit/**/*.js': [ 'browserify' ]
     },

    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],

    // web server port
    port: 9876,

    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_DEBUG,

    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Chrome','Firefox'],

    browserify: {
        transform: ['proxyquire-universal']
    },

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    // Concurrency level
    // how many browser should be started simultanous
    concurrency: Infinity
      })
       }

**Comment by bendrucker** [comment]
proxyquire-universal is not a transform, it's a plugin
