### ISSUE TITLE
Different behavior from proxyquire 

### ISSUE THREAD

**Issue by kgryte** [bendrucker/proxyquire-universal#18]
Module file `./lib/foo.js`:

``` javascript
var bool = require( 'my-dependency' );
if ( bool ) {
  module.exports = 1;
} else {
  module.exports = 0;
}
```

Test file `./test/test.js`:

``` javascript
var tape = require( 'tape' );
var proxyquire = require( 'proxyquire' );

tape( 'beep', function test( t ) {
  var dep = proxyquire( './../lib/foo.js', {
    'my-dependency': true
  };
  t.equal( dep, 1, 'equals 1' );
  t.end();
});

tape( 'boop', function test( t ) {
  var dep = proxyquire( './../lib/foo.js', {
    'my-dependency': false
  };
  t.equal( dep, 0, 'equals 0' ); // fails
  t.end();
});
```

Test invocation:

``` bash
./node_modules/.bin/browserify -p ./node_modules/proxyquire-universal test/*.js | ./node_modules/.bin/testling | ./node_modules/.bin/tap-spec
```

When the tests run in `Node`, the tests pass. When the tests run in the browser via `proxyquire-universal` and `proxyquirify`, the tests fail, as `my-dependency` never gets set to `false`. 

Any suggestions for how to fix this problem given that `proxyquire-universal` does not support forced reloading of modules?

**Comment by bendrucker** [comment]
No suggestions unfortunately

There have been some proposals for resetting the cache with proxyquireify (https://github.com/thlorenz/proxyquireify/pull/41) but they've always created substantial API divergence between proxyquire and proxyquireify. 

This is a documented limitation (https://github.com/bendrucker/proxyquire-universal#unsupported-proxyquire-features). I'm not sure if it's even possible to implement `noPreserveCache` for proxyquireify.

**Comment by kgryte** [comment]
With `proxyquire`, the option `noPreserveCache` is available, but it is not used here. It seems by default `proxyquire` allows me to overwrite the exported value of a proxied dependency. So a question is why does the default behavior change when using `proxyquire-universal`?

**Comment by bendrucker** [comment]
proxyquire-universal isn't involved here. It's just a matter of behavioral differences between proxyquireify and proxyquire.

**Comment by kgryte** [comment]
Rog.

**Comment by kgryte** [comment]
I believe the behavioral difference is related to https://github.com/thlorenz/proxyquireify/issues/32. If I set the stub in the second test to a `truthy` value, the stub is used. The issue seems to be that `proxyquire` will accept a stub having a value of `false`, while `proxyquirify` does not.
