### ISSUE TITLE
ES6 compatibility

### ISSUE THREAD

**Issue by 1v4nx** [bendrucker/proxyquire-universal#19]
Currently, the transformation only works with `require('proxyquire')` statements, not with `import proxyquire from 'proxyquire'` ones.

Also, mixing both `require` and `import` statements on a single file seems to break with `SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'` error. Though, that seems to be an issue with proxyquireify's browserify plugin.

**Comment by bendrucker** [comment]
How is an `import` statement supposed to work in the first place? Browserify isn't going to handle `import` keywords either so I don't see how this is specific to this plugin. Those statements need to be transpiled to `require` to actually work.

**Comment by bendrucker** [comment]
Closing b/c none of this seems proxyquireify related. That error you shared is from babel.
