### ISSUE TITLE
Change from peerDep to regular

### ISSUE THREAD

**Issue by bendrucker** [bendrucker/proxyquire-universal#5]
Proposed in https://github.com/thlorenz/proxyquireify/issues/20#issuecomment-69638861

**Comment by bendrucker** [comment]
@thlorenz Right now this can't be done. Were you thinking that I'd switch things over to asking users to `require('proxyquire-universal')` from their code versus shimming `require('proxyquire')`? By directly depending Node/Browserify won't be able to resolve `require('proxyquire')`.

**Comment by thlorenz** [comment]
Ah, yes you are right, oh well, gonna have to stick with peerDeps then.
