### ISSUE TITLE
Messes with coverage summary using browserify-istanbul

### ISSUE THREAD

**Issue by jamestalmage** [bendrucker/proxyquire-universal#8]
Basically, for every `require` in my project, istanbul reports an extra uncovered branch. So if there are 3 fully covered branches in my actual code and 3 `require(...)` statements, the summary reports coverage on `3 / 6` branches. If I switch to using `proxyquireify` directly, the issue disappears.

See `coverage` branch on: https://github.com/jamestalmage/karma-browserify-proxyquire-issue. It does **not** display the same issue I am experiencing on a closed source project. But the config is as close as possible to what I'm using. I'm moving forward with browser only tests for now, but I'll get back to creating a minimal reproduction at some point.

**Comment by bendrucker** [comment]
I don't see how proxyquire could affect this. If you're using browserify-shim that can cause this. It's transforming a `require` statement into a ternary. The solution is to cover your code before you run b-shim.

**Comment by jamestalmage** [comment]
I thought of that, and dropped browserify-shim (I wrote my own `module.exports = global` shims). Problem still exists, I will investigate further.

**Comment by jamestalmage** [comment]
You were right. It was browserify-shim

**Comment by bendrucker** [comment]
> You were right. It was browserify-shim

:smile: 

Knew it right away because I was hitting the same exact issue months ago
