### ISSUE TITLE
Update proxyquireify dep

### ISSUE THREAD

**Issue by stuartsan** [bendrucker/proxyquire-universal#9]
Would it be ok to update the proxyquireify dev / peer dep in package.json to ensure that >= 1.2 is used, to take advantage of the fixed issue described here https://github.com/thlorenz/proxyquireify/issues/21 and fixed by https://github.com/thlorenz/proxyquireify/commit/0048897ea82299a222a510828d2be4d04158a38f ?

**Comment by bendrucker** [comment]
I'm going to keep the peers the way they are now. peerDeps are there for specifying API-level compatibility. Since the user is responsible for installing the peers, I'm gonna say that they're responsible for installing updates in the peers as well.
